name: CI

on:
  push:
    paths:
      - 'docs/diagrams/**.mmd'

jobs:
  lint_mermaid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Lint Mermaid diagram
        run: |
          # render to a temporary SVG (valid extension)
          mmdc -i docs/diagrams/vpn-architecture.mmd -o temp-vpn-architecture.svg
          # if the linter passes, we can delete the file
          rm temp-vpn-architecture.svg

