name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/diagrams/**.mmd'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  lint_mermaid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Lint Mermaid diagram
        run: |
          # render to a temp SVG (must end in .svg)
          mmdc \
            -i docs/diagrams/vpn-architecture.mmd \
            -o docs/diagrams/vpn-architecture.lint.svg \
            --puppeteer-args "--no-sandbox --disable-setuid-sandbox"

          # clean up
          rm docs/diagrams/vpn-architecture.lint.svg
